# Generated by Django 4.1.3 on 2022-12-05 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_last_name", models.CharField(max_length=50)),
                ("candidate_first_name", models.CharField(max_length=50)),
                ("candidate_address", models.CharField(max_length=150)),
                (
                    "candidate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("candidate_email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_address", models.CharField(max_length=150)),
                (
                    "company_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("company_email", models.EmailField(max_length=100)),
                ("company_poc", models.CharField(max_length=50)),
                ("company_acknowledge", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=50)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("AA", "Please pick one"),
                            ("HE", "Health"),
                            ("OP", "Operations"),
                            ("MA", "Marketing"),
                            ("SA", "Sales"),
                            ("TE", "Tech"),
                        ],
                        max_length=2,
                    ),
                ),
                ("job_description", models.TextField(max_length=2500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("candidate_applied", models.BooleanField(default=False)),
                (
                    "related_employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
