# Generated by Django 4.1.3 on 2022-12-01 18:39

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_last_name", models.CharField(max_length=50)),
                ("candidate_first_name", models.CharField(max_length=50)),
                ("candidate_address", models.CharField(max_length=150)),
                (
                    "candidate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("candidate_email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_address", models.CharField(max_length=150)),
                (
                    "company_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("company_email", models.EmailField(max_length=100)),
                ("company_poc", models.CharField(max_length=50)),
                ("company_acknowledge", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_title", models.CharField(max_length=50)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("HE", "Health"),
                            ("OP", "Operations"),
                            ("MA", "Marketing"),
                            ("SA", "Sales"),
                            ("TE", "Tech"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("job_description", models.TextField(max_length=2500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("candidate_applied", models.BooleanField(default=False)),
            ],
        ),
    ]
