# Generated by Django 4.1.3 on 2022-12-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bridgehead_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="candidate_applied",),
    ]
