# Generated by Django 4.1.3 on 2022-12-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bridgehead_app", "0002_remove_job_candidate_applied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="related_employer", new_name="recruiter",
        ),
    ]
