# Generated by Django 4.1.3 on 2022-12-07 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bridgehead_app", "0003_rename_related_employer_job_recruiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
