# Generated by Django 4.1.3 on 2022-12-08 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bridgehead_app", "0004_job_candidate"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="candidate",),
        migrations.AddField(
            model_name="job",
            name="candidate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="candidate_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
