# Generated by Django 4.1.3 on 2022-12-08 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bridgehead_app", "0005_remove_job_candidate_job_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="candidate",
            field=models.ManyToManyField(
                blank=True, related_name="candidate_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
